"""Constrain a solve to deliver a published plan's generation mix.

Reads --plan-quota-file, a CSV with columns period, category, bound
(min|max), gwh, and constrains annual generation accordingly:

  usolar    DispatchGen of CentralTrackingPV projects
  offshore  DispatchGen of OffshoreWind
  wind      DispatchGen of Onshore + Offshore wind combined
  fossil    DispatchGen of LSFO / Diesel / LNG / multiple-fuel projects
  hydrogen  DispatchFuelCellMW (the hawaii.hydrogen module)

Floors (min) make the model build and run at least the plan's clean mix;
the fossil band pins its thermal reliance. Dispatch, storage, and all other
choices stay optimized, so the solved cost is a lower bound on what the
plan's mix costs in this framework. Used by the plan price-tag runs
(scenarios/scenarios_plan_price.txt); quota files are generated by
build/build_plan_quotas.py.
"""
import csv

from pyomo.environ import Constraint, Set

CAT_SOURCES = ("LSFO", "Diesel", "LNG", "multiple")


def define_arguments(argparser):
    argparser.add_argument("--plan-quota-file", default=None,
                           help="CSV of generation quotas (period, category, "
                                "bound, gwh); omit to disable")


def define_components(m):
    if not getattr(m.options, "plan_quota_file", None):
        return
    with open(m.options.plan_quota_file) as f:
        quotas = [(int(r["period"]), r["category"], r["bound"],
                   float(r["gwh"])) for r in csv.DictReader(f)]

    def gens(m, cat):
        if cat == "usolar":
            return [g for g in m.GENERATION_PROJECTS
                    if "CentralTrackingPV" in g]
        if cat == "offshore":
            return [g for g in m.GENERATION_PROJECTS
                    if m.gen_tech[g] == "OffshoreWind"]
        if cat == "wind":
            return [g for g in m.GENERATION_PROJECTS
                    if m.gen_tech[g] in ("OffshoreWind", "OnshoreWind")]
        if cat == "fossil":
            return [g for g in m.GENERATION_PROJECTS
                    if m.gen_energy_source[g] in CAT_SOURCES]
        raise ValueError(cat)

    def annual_mwh(m, p, cat):
        if cat == "hydrogen":
            return sum(m.DispatchFuelCellMW[z, t] * m.tp_weight_in_year[t]
                       for z in m.LOAD_ZONES for t in m.TPS_IN_PERIOD[p])
        return sum(m.DispatchGen[g, t] * m.tp_weight_in_year[t]
                   for g in gens(m, cat) for t in m.TPS_IN_PERIOD[p]
                   if (g, t) in m.GEN_TPS)

    m.PLAN_QUOTA_ROWS = Set(initialize=list(range(len(quotas))),
                            dimen=1, ordered=True)

    def quota_rule(m, i):
        p, cat, bound, gwh = quotas[i]
        if p not in m.PERIODS:
            return Constraint.Skip
        expr = annual_mwh(m, p, cat)
        if bound == "min":
            return expr >= gwh * 1000.0
        return expr <= gwh * 1000.0

    m.Plan_Mix_Quota = Constraint(m.PLAN_QUOTA_ROWS, rule=quota_rule)
    print(f"Plan mix quotas active: {len(quotas)} rows from "
          f"{m.options.plan_quota_file}")
