# Interactive explorer for the Oʻahu electricity study (pre-v1.02).
# Runs as a serverless shinylive site; data in data/ is generated by
# build/build_explorer_data.py from the full solve fleet.

library(shiny)
library(bslib)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(jsonlite)
library(scales)
library(plotly)

scen   <- read_csv("data/scenarios.csv", show_col_types = FALSE)
gen    <- read_csv("data/generation.csv", show_col_types = FALSE)
costs  <- read_csv("data/costs.csv", show_col_types = FALSE)
hourly <- read_csv("data/dispatch_hourly.csv", show_col_types = FALSE)
meta   <- fromJSON("data/meta.json")

TECH_COLORS <- c(
  "Oil" = "#8c564b", "LNG" = "#7f7f7f", "Waste-to-energy" = "#bcbd22",
  "Geothermal (EGS)" = "#d62728", "Onshore wind" = "#1f77b4",
  "Offshore wind" = "#17becf", "Utility solar" = "#ff7f0e",
  "Distributed solar (netted)" = "#ffbb78",
  "Distributed solar (modeled)" = "#f7e08a",
  "Battery storage" = "#2ca02c", "Other" = "#c7c7c7"
)
TECH_ORDER <- names(TECH_COLORS)

HOUR_COLORS <- c(
  "Geothermal" = "#756bb1", "Waste-to-energy" = "#7f7f7f",
  "Thermal (oil/LNG)" = "#843c39", "Wind" = "#5fa2ce",
  "Utility solar" = "#f2c744", "Rooftop solar" = "#f7e08a",
  "Battery discharge (net)" = "#2ca02c",
  "Curtailed solar & wind" = "#d9d9d9"
)
# withdrawals drawn below zero (stored as negative MW in the extract); the
# demand line is retail demand only, so these account for the generation
# stack topping the line
BELOW_COLORS <- c("Hydrogen production" = "#e377c2",
                  "EV charging" = "#17becf",
                  "Battery charging (net)" = "#2ca02c")

OILS  <- c("Market 10th percentile", "Brent futures", "EIA reference",
           "Market 90th percentile")
# solar_mult is relative to the study baseline (1.2x mainland ATB), so the
# premiums over mainland costs are 20% / 80% / 104%
SOLAR_LABELS <- c("1" = "20% Hawaiʻi premium",
                  "1.5" = "80% Hawaiʻi premium",
                  "1.7" = "104% Hawaiʻi premium")
TRAJS <- unique(scen$trajectory)
CONFIG_ORDER <- scen |> distinct(config_label) |> pull(config_label)
# scenario dropdown choices: plain-English label -> scenario id
SCEN_CHOICES <- local({
  s <- scen |> arrange(short_label)
  setNames(s$scenario, s$short_label)
})
desc_of <- function(id) scen$description[scen$scenario == id][1]
short_of <- function(id) scen$short_label[scen$scenario == id][1]

# Published-plan cells constrain generation to somebody else's plan. Each plan
# is paired with the rooftop trajectory its own customer-solar assumptions
# track; shown on any other trajectory it has been RESCALED, and the footnote
# below says so wherever such a cell can appear. Without it the two variants
# look like the same plan costing different amounts.
RESCALE_NOTE <- paste(
  "<b>Rescaled plan.</b> A published plan states its generation mix for the",
  "island demand <i>it</i> assumed. To price that mix here it is converted to",
  "shares and applied to the grid demand this rooftop trajectory leaves for",
  "the utility to serve — that conversion is what \u201crescaled\u201d means.",
  "A plan shown on its own trajectory is rescaled only for the modest",
  "difference between its demand forecast and ours. A plan marked",
  "<i>rescaled to this trajectory</i> has been moved onto a different rooftop",
  "trajectory altogether, so that the two plans can be compared on common",
  "ground: the accelerated and base trajectories leave roughly 5,400 and",
  "7,200 GWh of grid demand in 2045, and a plan costs more simply by serving",
  "more. Compare a rescaled cell with the other plan on the <i>same</i>",
  "trajectory; do not compare it with the same plan on its home trajectory."
)

rescale_note <- function(ids) {
  # tolerate an older extract that predates the column, so a data/app version
  # skew degrades to "no note" rather than a broken tab
  if (is.null(scen$rescaled)) return(NULL)
  ids <- ids[!is.na(ids)]
  if (!length(ids)) return(NULL)
  if (!any(scen$rescaled[scen$scenario %in% ids] == 1)) return(NULL)
  tags$div(class = "small text-muted mt-2 border-top pt-2", HTML(RESCALE_NOTE))
}

axis_selectors <- function(id, mult = TRUE) {
  tagList(
    selectInput(paste0(id, "_traj"), "Rooftop trajectory", TRAJS,
                selected = "Conservative rooftop (base)"),
    selectInput(paste0(id, "_oil"), "Oil-price case",
                intersect(OILS, unique(scen$oil_label)),
                selected = "EIA reference"),
    if (mult) selectInput(paste0(id, "_mult"), "Utility solar cost",
                          local({
                            sm <- sort(unique(scen$solar_mult))
                            setNames(sm, SOLAR_LABELS[as.character(sm)])
                          }), selected = 1.0),
    selectInput(paste0(id, "_screen"), "Land screen",
                unique(scen$land_screen), selected = "Reference"),
    selectInput(paste0(id, "_basis"), "Solar/battery cost basis",
                unique(scen$solar_basis), selected = "ATB Moderate")
  )
}

filter_axes <- function(df, input, id, mult = TRUE) {
  out <- df |>
    filter(trajectory == input[[paste0(id, "_traj")]],
           oil_label == input[[paste0(id, "_oil")]],
           land_screen == input[[paste0(id, "_screen")]],
           solar_basis == input[[paste0(id, "_basis")]])
  if (mult) out <- filter(out, solar_mult == input[[paste0(id, "_mult")]])
  out
}

ui <- page_navbar(
  title = "Oʻahu Electricity Futures — results explorer",
  theme = bs_theme(bootswatch = "flatly"),
  header = tags$div(
    class = "alert alert-warning py-1 px-3 mb-0 small",
    sprintf(paste0("Pre-release (%s), open for comment — results may change. ",
                   "Data: %s solved scenarios (%s scenario-matrix cells and %s ",
                   "published-plan cells), %s at 0.1%% optimality; generated %s."),
            meta$version, meta$scenarios,
            if (is.null(meta$matrix_cells)) "—" else meta$matrix_cells,
            if (is.null(meta$plan_cells)) "—" else meta$plan_cells,
            meta$refined_010, meta$generated_hst)
  ),

  nav_panel("System costs",
    layout_sidebar(
      sidebar = sidebar(
        axis_selectors("c"),
        checkboxInput("c_delta", "Show difference vs no-new-plant", TRUE),
        checkboxInput("c_conv", "Charge conversion capital ($0.45B) to conversion cases", TRUE)
      ),
      card(card_header("Total 2027–2050 system cost (present value, billion 2024$)"),
           uiOutput("cost_plot_ui"),
           uiOutput("cost_note")),
      card(card_header("Table"), tableOutput("cost_table"))
    )
  ),

  nav_panel("Generation mix",
    layout_sidebar(
      sidebar = sidebar(
        axis_selectors("g"),
        uiOutput("g_config_ui"),
        radioButtons("g_metric", "Metric",
                     c("Energy (GWh/yr)" = "energy_gwh",
                       "Capacity (MW)" = "capacity_mw",
                       "Emissions (kt CO2/yr)" = "emissions_tco2"))
      ),
      card(card_header(textOutput("g_title")),
           uiOutput("g_desc"),
           plotOutput("mix_plot", height = 460),
           uiOutput("g_note"))
    )
  ),

  nav_panel("Compare",
    layout_sidebar(
      sidebar = sidebar(
        selectInput("cmp_a", "Scenario A", SCEN_CHOICES,
                    selected = "nlv2b_C4_NOTHERMAL_refbrent"),
        selectInput("cmp_b", "Scenario B", SCEN_CHOICES,
                    selected = "nlv2b_wb_C6_LNG500_refbrent")
      ),
      card(card_header(textOutput("cmp_head")),
           uiOutput("cmp_desc"),
           plotOutput("cmp_plot", height = 430),
           uiOutput("cmp_note")),
      card(tableOutput("cmp_table"))
    )
  ),

  nav_panel("Emissions",
    layout_sidebar(
      sidebar = sidebar(
        axis_selectors("e"),
        uiOutput("e_configs_ui")
      ),
      card(card_header("Combustion CO2 by period (Mt/yr; excludes upstream methane)"),
           plotOutput("em_plot", height = 440),
           uiOutput("em_note"))
    )
  ),

  nav_panel("Hourly dispatch",
    layout_sidebar(
      sidebar = sidebar(
        selectInput("h_scen", "Scenario",
                    SCEN_CHOICES[SCEN_CHOICES %in% unique(hourly$scenario)],
                    selected = "nlv2b_C4_NOTHERMAL_refbrent"),
        radioButtons("h_day", "2035 sample day",
                     setNames(names(meta$sample_days),
                              paste0(unlist(meta$sample_days), " — ",
                                     names(meta$sample_days))))
      ),
      card(card_header("Hourly generation and demand (MW), 2035"),
           uiOutput("h_desc"),
           plotOutput("hr_plot", height = 460))
    )
  ),

  nav_panel("All solves",
    layout_sidebar(
      sidebar = sidebar(
        checkboxGroupInput("a_oil", "Oil cases",
                           intersect(OILS, unique(scen$oil_label)),
                           selected = intersect(OILS, unique(scen$oil_label))),
        checkboxGroupInput("a_traj", "Trajectories", TRAJS, selected = TRAJS)
      ),
      card(card_header(sprintf(
        "Every solved scenario (%s) — hover for details", meta$scenarios)),
        plotlyOutput("all_plot", height = 560))
    )
  ),

  nav_panel("About", uiOutput("about"))
)

server <- function(input, output, session) {

  # ---- System costs ----
  cost_data <- reactive({
    d <- filter_axes(scen, input, "c")
    shiny::validate(shiny::need(nrow(d) > 0, "No solved scenarios match this selection."))
    if (input$c_conv) d <- mutate(d, total_cost_bn = total_cost_bn + conv_capital_bn)
    # collapse the JERA capital band: bar at bare-EPC-to-+20% midpoint
    d |>
      group_by(config_label) |>
      summarise(lo = min(total_cost_bn), hi = max(total_cost_bn),
                mid = (lo + hi) / 2, n = n(), .groups = "drop")
  })

  output$cost_note <- renderUI(
    rescale_note(filter_axes(scen, input, "c")$scenario))

  # size the bar chart to the number of configurations so nothing is cramped
  output$cost_plot_ui <- renderUI({
    plotOutput("cost_plot", height = max(480, 70 * nrow(cost_data()) + 130))
  })

  output$cost_plot <- renderPlot({
    d <- cost_data()
    base <- d$mid[d$config_label == "No new fuel plant"]
    if (input$c_delta && length(base) == 1) {
      d <- mutate(d, mid = mid - base, lo = lo - base, hi = hi - base)
      ylab <- "vs no-new-plant (billion 2024$)"
    } else ylab <- "billion 2024$ (PV 2027)"
    ggplot(d, aes(reorder(config_label, mid), mid)) +
      geom_col(fill = "#31708c", width = 0.65) +
      geom_errorbar(aes(ymin = lo, ymax = hi), width = 0.2, linewidth = 0.5) +
      geom_hline(yintercept = 0, linewidth = 0.4) +
      geom_text(aes(label = sprintf("%+.2f", mid),
                    vjust = ifelse(mid >= 0, -0.5, 1.3)), size = 3.4) +
      coord_flip() +
      labs(x = NULL, y = ylab,
           caption = "Whiskers: JERA capital, bare-EPC to +20%, where both are solved.") +
      theme_minimal(base_size = 13)
  })

  output$cost_table <- renderTable({
    cost_data() |>
      transmute(Configuration = config_label,
                `Total ($B)` = sprintf("%.2f", mid),
                `Band` = ifelse(hi - lo > 1e-6,
                                sprintf("[%.2f, %.2f]", lo, hi), "—"))
  })

  # ---- Generation mix ----
  output$g_config_ui <- renderUI({
    opts <- filter_axes(scen, input, "g") |> pull(config_label) |> unique()
    selectInput("g_config", "Configuration", opts,
                selected = intersect("No new fuel plant", opts)[1])
  })

  g_scen <- reactive({
    req(input$g_config)
    d <- filter_axes(scen, input, "g") |>
      filter(config_label == input$g_config, jera_capital == "bare-EPC")
    shiny::validate(shiny::need(nrow(d) >= 1, "No solved scenario matches this selection."))
    d$scenario[1]
  })

  output$g_note <- renderUI(rescale_note(g_scen()))

  output$g_title <- renderText(short_of(g_scen()))

  output$g_desc <- renderUI({
    div(class = "px-3 small",
        p(class = "mb-1", desc_of(g_scen())),
        p(class = "text-muted mb-0", paste("Model cell:", g_scen())))
  })

  output$mix_plot <- renderPlot({
    d <- gen |> filter(scenario == g_scen()) |>
      mutate(value = .data[[input$g_metric]] /
               ifelse(input$g_metric == "emissions_tco2", 1000, 1),
             tech = factor(tech, levels = rev(TECH_ORDER)))
    if (input$g_metric != "capacity_mw")
      d <- filter(d, tech != "Battery storage")
    # drop empty techs (legend clutter) and never stack a negative band
    d <- d |> group_by(tech) |> filter(sum(abs(value)) > 0.5) |>
      ungroup() |> mutate(value = pmax(value, 0), tech = droplevels(tech))
    # complete the grid: geom_area garbles the stack when a tech (e.g. LNG)
    # has no row in the periods where it is zero
    d <- d |> complete(period = sort(unique(d$period)), tech,
                       fill = list(value = 0))
    ggplot(d, aes(period, value, fill = tech)) +
      geom_area(alpha = 0.92) +
      scale_fill_manual(values = TECH_COLORS, name = NULL) +
      scale_x_continuous(breaks = sort(unique(d$period))) +
      labs(x = NULL, y = names(which(c(
        "Energy (GWh/yr)" = "energy_gwh", "Capacity (MW)" = "capacity_mw",
        "Emissions (kt CO2/yr)" = "emissions_tco2") == input$g_metric))) +
      theme_minimal(base_size = 13) + theme(legend.position = "right")
  })

  # ---- Compare ----
  output$cmp_note <- renderUI(rescale_note(c(input$cmp_a, input$cmp_b)))

  output$cmp_head <- renderText({
    a <- scen[scen$scenario == input$cmp_a, ]
    b <- scen[scen$scenario == input$cmp_b, ]
    sprintf("A: %s ($%.2fB)   |   B: %s ($%.2fB)   |   B − A: %+.2fB",
            short_of(input$cmp_a), a$total_cost_bn,
            short_of(input$cmp_b), b$total_cost_bn,
            b$total_cost_bn - a$total_cost_bn)
  })

  output$cmp_desc <- renderUI({
    div(class = "px-3 small",
        p(class = "mb-1", strong("A: "), desc_of(input$cmp_a)),
        p(class = "mb-1", strong("B: "), desc_of(input$cmp_b)),
        p(class = "text-muted mb-0",
          paste("Model cells:", input$cmp_a, "|", input$cmp_b)))
  })

  output$cmp_plot <- renderPlot({
    d <- gen |>
      filter(scenario %in% c(input$cmp_a, input$cmp_b),
             tech != "Battery storage") |>
      mutate(which = ifelse(scenario == input$cmp_a, "A", "B"),
             tech = factor(tech, levels = rev(TECH_ORDER)),
             energy_gwh = pmax(energy_gwh, 0)) |>
      group_by(tech) |> filter(sum(abs(energy_gwh)) > 0.5) |> ungroup() |>
      mutate(tech = droplevels(tech)) |>
      group_by(which) |>
      complete(period = sort(unique(gen$period)), tech,
               fill = list(energy_gwh = 0)) |>
      ungroup()
    ggplot(d, aes(period, energy_gwh, fill = tech)) +
      geom_area(alpha = 0.92) +
      facet_wrap(~which, ncol = 2) +
      scale_fill_manual(values = TECH_COLORS, name = NULL) +
      labs(x = NULL, y = "GWh per year") +
      theme_minimal(base_size = 13)
  })

  output$cmp_table <- renderTable({
    gen |>
      filter(scenario %in% c(input$cmp_a, input$cmp_b), period == 2050,
             tech != "Battery storage") |>
      mutate(which = ifelse(scenario == input$cmp_a, "A", "B")) |>
      group_by(tech) |>
      summarise(`A 2050 GWh` = sum(energy_gwh[which == "A"]),
                `B 2050 GWh` = sum(energy_gwh[which == "B"]), .groups = "drop") |>
      filter(`A 2050 GWh` + `B 2050 GWh` > 0)
  })

  # ---- Emissions ----
  output$e_configs_ui <- renderUI({
    opts <- filter_axes(scen, input, "e") |> pull(config_label) |> unique()
    checkboxGroupInput("e_configs", "Configurations", opts,
                       selected = intersect(c("No new fuel plant",
                                              "JERA LNG plant, 500 MW"), opts))
  })

  output$em_note <- renderUI({
    req(input$e_configs)
    rescale_note(filter_axes(scen, input, "e") |>
                   filter(config_label %in% input$e_configs) |>
                   pull(scenario))
  })

  output$em_plot <- renderPlot({
    req(input$e_configs)
    picks <- filter_axes(scen, input, "e") |>
      filter(config_label %in% input$e_configs, jera_capital == "bare-EPC")
    shiny::validate(shiny::need(nrow(picks) > 0, "No solved scenarios match."))
    d <- gen |>
      inner_join(select(picks, scenario, config_label), by = "scenario") |>
      group_by(config_label, period) |>
      summarise(mt = sum(emissions_tco2) / 1e6, .groups = "drop")
    ggplot(d, aes(period, mt, color = config_label)) +
      geom_line(linewidth = 1.1) + geom_point(size = 2) +
      labs(x = NULL, y = "Mt CO2 per year", color = NULL) +
      theme_minimal(base_size = 13) + theme(legend.position = "bottom")
  })

  # ---- Hourly dispatch ----
  output$h_desc <- renderUI({
    div(class = "px-3 small",
        p(class = "mb-1", desc_of(input$h_scen)),
        p(class = "text-muted mb-0", paste("Model cell:", input$h_scen)))
  })

  output$hr_plot <- renderPlot({
    d <- hourly |> filter(scenario == input$h_scen, day == input$h_day)
    shiny::validate(shiny::need(nrow(d) > 0, "No hourly data for this scenario."))
    # The model solves two-hour blocks; draw each block flat (stepped bars,
    # not interpolated areas) so adjacent blocks with opposite battery flows
    # do not smear into an apparent simultaneous charge and discharge.
    stacks <- d |> filter(series %in% names(HOUR_COLORS)) |>
      mutate(series = factor(series, levels = rev(names(HOUR_COLORS))))
    dem <- d |> filter(series == "Demand")
    dem <- bind_rows(dem, dem |> slice_max(hour, n = 1) |> mutate(hour = 24))
    below <- d |> filter(series %in% names(BELOW_COLORS)) |>
      group_by(series) |> filter(any(mw != 0)) |> ungroup() |>
      mutate(series = factor(series, levels = names(BELOW_COLORS)))
    ggplot() +
      geom_col(data = stacks, aes(hour + 1, mw, fill = series),
               width = 2, alpha = 0.9) +
      geom_col(data = below, aes(hour + 1, mw, fill = series),
               width = 2, alpha = 0.45) +
      geom_step(data = dem, aes(hour, mw), linewidth = 1.1) +
      geom_hline(yintercept = 0, linewidth = 0.4) +
      scale_fill_manual(values = c(HOUR_COLORS, BELOW_COLORS), name = NULL) +
      scale_x_continuous(breaks = seq(0, 24, 4)) +
      labs(x = "Hour of day", y = "MW",
           # wrap the note and left-align it inside the plot area so it does
           # not extend past the left edge of the screen
           caption = paste(strwrap(paste0(
             "Each bar is one two-hour model block (the model's time ",
             "resolution). Black step line: retail demand. Bars below zero ",
             "are loads the demand line does not include: net battery ",
             "charging, flexible EV charging, and hydrogen production where ",
             "built — they account for generation topping the demand line. ",
             "Battery flows are shown net: in surplus hours the optimizer ",
             "may charge and discharge simultaneously (a costless way to ",
             "shed surplus), which the net view removes; the energy lost ",
             "that way is counted as curtailment. Curtailed solar & wind is ",
             "potential output above what was dispatched."), width = 95),
             collapse = "\n")) +
      theme_minimal(base_size = 13) +
      theme(plot.caption = element_text(hjust = 0, size = 9,
                                        margin = margin(t = 8)),
            plot.caption.position = "plot")
  })

  # ---- All solves ----
  output$all_plot <- renderPlotly({
    d <- scen |>
      filter(oil_label %in% input$a_oil, trajectory %in% input$a_traj)
    shiny::validate(shiny::need(nrow(d) > 0, "Nothing selected."))
    set.seed(1)
    d <- d |>
      mutate(yn = as.numeric(factor(config_label, levels = CONFIG_ORDER)) +
               runif(n(), -0.18, 0.18),
             tip = paste0(short_label, "<br>$",
                          sprintf("%.2f", total_cost_bn), "B<br>",
                          scenario))
    plot_ly(d, x = ~total_cost_bn, y = ~yn, color = ~oil_label,
            symbol = ~trajectory, text = ~tip, hoverinfo = "text",
            type = "scatter", mode = "markers",
            marker = list(size = 8, opacity = 0.75)) |>
      layout(yaxis = list(tickvals = seq_along(CONFIG_ORDER),
                          ticktext = CONFIG_ORDER, title = ""),
             xaxis = list(title = "Total system cost (billion 2024$, PV 2027)"),
             legend = list(orientation = "h"))
  })

  # ---- About ----
  output$about <- renderUI({
    tagList(
      div(class = "container py-4", style = "max-width: 780px",
        h3("About this explorer"),
        p(sprintf(paste0(
          "Every chart is drawn from %s solved scenarios of the Oʻahu ",
          "capacity-expansion study (Switch 2.0.9/CPLEX), release %s, ",
          "data generated %s at repository commit %s."),
          meta$scenarios, meta$version, meta$generated_hst, meta$commit)),
        p(HTML(paste0(
          "The report, methods, inputs, and full scenario definitions are in the ",
          "<a href='https://github.com/mikejrob/oahu-electricity-future'>",
          "public repository</a>. Comments are invited during the pre-release ",
          "window — see COMMENT_POLICY.md there."))),
        h5("Published plans"),
        p(HTML(paste0(
          "Most scenarios here are builds the model chose: it was given costs ",
          "and constraints and picked the cheapest system. Four are not. The ",
          "cells labelled <b>Published plan</b> hold generation to a mix ",
          "somebody else published — Hawaiian Electric's integrated grid plan ",
          "in its base and land-constrained scenarios, and the Hawai\u02bbi ",
          "State Energy Office's alternative-fuels study in its oil and LNG ",
          "cases. Their cost is what it takes to run that mix in this ",
          "framework, so the gap against the least-cost build on the same ",
          "settings is the plan's price tag rather than a difference of ",
          "opinion about costs."))),
        p(HTML(paste0(
          "Two consequences are worth knowing. Each plan's clean categories ",
          "are pinned to its own levels, but the split between onshore and ",
          "offshore wind is not reproducible here — onshore is capped at ",
          "150 MW by the county setback screen, so offshore stands in for the ",
          "onshore the plans assume, and only the wind <i>total</i> matches. ",
          "And from 2045 the plans lean on firm clean energy that they carry ",
          "as biofuel in one case and imported hydrogen in another; these ",
          "cells are held to the quantity, not the carrier, and choose the ",
          "cheaper of the two. They choose biofuel every time — there is no ",
          "surplus generation to make hydrogen from once solar and wind are ",
          "pinned to the plan's own levels."))),
        h5("Conventions"),
        tags$ul(
          tags$li("All dollars are real 2024$; totals are present values of",
                  " 2027–2050 system cost discounted to 2027 at 3 percent."),
          tags$li("Rooftop (distributed) solar and storage are netted out of",
                  " load before the model sees them, so they are not generators",
                  " it dispatches. The 'distributed solar (netted)' series in",
                  " the mix charts is the energy actually removed from load —",
                  " measured as gross load minus that trajectory's net load,",
                  " period by period — so it matches the model inputs exactly.",
                  " It counts grid-visible output only: rooftop generation that",
                  " never crosses the meter is excluded, so the series sits",
                  " below what the panels physically produce."),
          tags$li("Thermal generation is split between oil and LNG in",
                  " proportion to fuel energy use; emissions are split by the",
                  " same shares (an approximation)."),
          tags$li("Conversion scenarios exclude plant-conversion capital in",
                  " the model; the optional $0.45B charge is a 2016-benchmark",
                  " estimate (report Section 4.7)."),
          tags$li("Emissions are combustion CO2 only; upstream methane is",
                  " discussed in the report."),
          tags$li("Hourly battery flows are shown net of simultaneous",
                  " charge/discharge (a costless surplus-shedding artifact in",
                  " the optimizer); curtailment is shown explicitly as",
                  " potential output above dispatch."),
          tags$li("Scenarios at 0.25 percent optimality are being refined to",
                  " 0.1 percent on an ongoing basis; small differences between",
                  " scenarios can be within solver tolerance.")),
        p(class = "text-muted small",
          "First load takes a while: the app runs entirely in your browser",
          " (webR/shinylive); nothing is sent to a server.")
      )
    )
  })
}

shinyApp(ui, server)
